language: node_js
services:
  - docker
script:
- npm test
after_success:
  - docker login -u ${USERNAME} -p ${PASSWORD} ${REGISTRY}
  - docker build -t ${REGISTRY}/hotelmvp/web .
  - docker push ${REGISTRY}/hotelmvp/web
  - heroku run --app hotelmvp
