language: node_js
sudo: required
env:
  secure: "RC0tgvqD77n14GTrn85XYbbjHc3ZxOgXZ3+QDY1v9sGTI9kJMubw2YCIpgu8ABggweSBEXe4FadI3Smu2El2O6BKy6OTuFyBs7qYZpKuxNl7RfNzLCNvxBQt5ETajU+kp+CrIBcXc1Pvunoxqbn0RM/Zy8NVuit7t9elMYWSKUyMrs5f6SQtsjqw6Z/HxoF53uM1RWGlSbVJ9dvrdSERHgUJa24eSSG/LMg9+MVwWJfx1iPYcISQTEzeQx0o0SRxKNJMqAhSenxwnk4GoPJzNjs/XqKYi8fEm9k74kQ11qmjIyh0XUeiM+cUtxvf7BkqRMn/KAR8o4ZMLTssWenHRAmd/tIASpzckUlGGCAvzqHnPQ9eC3of/cggO4sQpd/5ZEHVoFFq8sxV3aJk/lrhJraRrw3yS/ueZpHd7ZZlQFTrwBJrpd+unti9EkqRbJEODteLYQDozPfMcEcQ+z8PQAl4PpmW64Wo6w8MVTqaTRaAvSuuPJGnbNMmGqIgU+adr/hMF5LctS6tXkPzrXzGLPpdV4iLKfEDnMJkWah0tUtuEXq+LRd3W2nMX0e4otsf5IEcHeSHQoKBm7EwTG0HFItM1r5RZmUFFLzOneuVpZztwMAqdLOnRcTrUdgYS7vmByK6CoRF4cFRRTSmflMxZYlD58QeCEFi4zvYG26s2t8="
services:
  - docker
before_install:
  - sudo curl https://cli-assets.heroku.com/install.sh | sh
install:
  - npm install
script:
  - npm test
after_success:
  - docker login -u ${USERNAME} -p ${HEROKU_API_KEY} ${REGISTRY}
  - docker build -t hotel_app .
  - docker tag hotel_app ${REGISTRY}/hotelmvp/web
  - docker push ${REGISTRY}/hotelmvp/web
  - heroku container:release web -a hotelmvp
