language: node_js
sudo: required
services:
  - docker
before_install:
  - sudo curl https://cli-assets.heroku.com/install.sh | sh
script:
- npm test
after_success:
  - docker login -u ${USERNAME} -p ${PASSWORD} ${REGISTRY}
  - docker build -t hotel_app .
  - docker tag hotel_app ${REGISTRY}/hotelmvp/web
  - docker images
  - docker push ${REGISTRY}/hotelmvp/web
  - heroku container:release web -a hotelmvp
